using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PausarPlayer : MonoBehaviour
{
    // Almacena la posici贸n X del jugador cuando colisiona con la barrera
    private float posicionXOriginal;

    void OnCollisionEnter2D(Collision2D collision)
    {
        // Verificar si el objeto que colision贸 con la barrera tiene el tag "Player"
        if (collision.gameObject.CompareTag("Player"))
        {
            // Obtener la posici贸n X actual del jugador
            posicionXOriginal = collision.transform.position.x;
        }
    }

    void OnCollisionStay2D(Collision2D collision)
    {
        // Verificar si el objeto que sigue colisionando con la barrera tiene el tag "Player"
        if (collision.gameObject.CompareTag("Player"))
        {
            // Mantener la posici贸n X del jugador
            Vector3 posicionActual = collision.transform.position;
            posicionActual.x = posicionXOriginal;
            collision.transform.position = posicionActual;
        }
    }
}
